### ISSUE TITLE
cant not find the version in maven repository

### ISSUE THREAD

**Issue by Mark-jk** [jloisel/elastic-crud#11]
Downloading: https://repo.maven.apache.org/maven2/com/jeromeloisel/db-repository-elasticsearch/5.6.3/db-repository-elasticsearch-5.6.3.pom
[WARNING] The POM for com.jeromeloisel:db-repository-elasticsearch:jar:5.6.3 is missing, no dependency information available

**Comment by jloisel** [comment]
True, i'm struggling to release it. Rultor somehow doesn't want to release it:
https://github.com/jloisel/elastic-crud/issues/10

**Comment by jloisel** [comment]
It's releasing, it should take a few hours to appear on Maven Central.
